language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
# give up the ability to use 'sudo' in exchange for getting access to
# the newer/faster/better-scaling travis infrastructure
sudo: false
before_install:
  # Escape Travis virtualenv
  - deactivate
  # See: http://conda.pydata.org/docs/travis.html
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n testenv python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - conda install pip nose coverage numpy scipy matplotlib Cython
  - pip install nose-cov
install:
  - python setup.py sdist
  - mkdir empty
  - cd empty
  - pip install ../dist/*
  - INSTALLDIR=$(python -c "import os; import pycam02ucs; print(os.path.dirname(pycam02ucs.__file__))")
script:
  - nosetests --all-modules --with-cov --cov-conf ../.coveragerc --cov-report term-missing --cov ${INSTALLDIR} pycam02ucs
after_success:
  - pip install coveralls && coveralls --rcfile=../.coveragerc
notifications:
  email:
  - njs@pobox.com
